# -*- coding: utf-8 -*-
"""02_Write_Path.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1AW0qSuESpe4nWCjNQLIPhk82ttD5KK

# Write Path in Apache Arrow

In this notebook we are going to understand how data actually gets
**written** in Apache Arrow format.

The write path in Arrow looks like this:

Data (list/dict)

↓

pa.array()  →  ArrayBuilder fills values into memory buffers

↓

pa.table()  →  Multiple arrays combined with a schema

↓

RecordBatch →  A chunk of rows ready to be sent or saved

↓

IPC File    →  Arrow's own file format saved to disk

IPC stands for **Inter-Process Communication**.  
It is the format Arrow uses to save data to disk or send it over a network.

Reference: https://arrow.apache.org/docs/python/ipc.html
"""

import pyarrow as pa
import pyarrow.ipc as ipc
import os

print("Libraries ready")

"""## Step 1 — Creating an Array (ArrayBuilder internally)

When we call `pa.array()`, Arrow internally uses something called
an **ArrayBuilder** to fill values one by one into a memory buffer.

We do not call ArrayBuilder directly in Python —
`pa.array()` handles it for us.

But it is important to know it exists because the C++ source code
`cpp/src/arrow/array/builder_primitive.h` is where this actually happens.

The builder does two things:
- fills the **value buffer** with actual numbers/strings
- fills the **validity bitmap** with 1 (valid) or 0 (null)
"""

int_array    = pa.array([10, 20, 30, 40, 50])
float_array  = pa.array([1.1, 2.2, 3.3, None, 5.5])
string_array = pa.array(["apple", "banana", None, "date", "elderberry"])

print("Integer array :", int_array)
print()
print("Float array   :", float_array)
print()
print("String array  :", string_array)
print()
print("Notice 'None' becomes null inside Arrow automatically")

"""## Step 2 — Looking at the actual memory buffers

After `pa.array()` is called, the data sits in **raw memory buffers**.

Every Arrow array has buffers:
- **Buffer 0** → validity bitmap (1 = value present, 0 = null)
- **Buffer 1** → actual values in raw bytes

For string arrays there is a third buffer:
- **Buffer 2** → the actual string characters

This is defined in the Arrow columnar spec:  
https://arrow.apache.org/docs/format/Columnar.html

"""

print("===== Integer Array Buffers =====")
for i, buf in enumerate(int_array.buffers()):
    if buf:
        print(f"  Buffer {i} → {buf.size} bytes → {bytes(buf)}")

print()
print("===== Float Array Buffers (has a null) =====")
for i, buf in enumerate(float_array.buffers()):
    if buf:
        print(f"  Buffer {i} → {buf.size} bytes → {bytes(buf)}")

print()
print("===== String Array Buffers =====")
for i, buf in enumerate(string_array.buffers()):
    if buf:
        print(f"  Buffer {i} → {buf.size} bytes")

print()
print("String arrays have 3 buffers:")
print("  Buffer 0 = validity bitmap")
print("  Buffer 1 = offsets (where each string starts and ends)")
print("  Buffer 2 = actual characters")

"""## Step 3 — Building a RecordBatch

A **RecordBatch** is a collection of arrays (columns) with a schema.  
It represents a **chunk of rows** — like a mini table.

Arrow processes data in RecordBatches rather than one row at a time.  
This is what makes it efficient for large datasets.

Think of it like this:
- Table = the full dataset
- RecordBatch = one page/chunk of that dataset

When writing to disk, Arrow writes **one RecordBatch at a time**.

Docs: https://arrow.apache.org/docs/python/generated/pyarrow.RecordBatch.html
"""

schema = pa.schema([
    pa.field("product", pa.string()),
    pa.field("units",   pa.int32()),
    pa.field("price",   pa.float64())
])

batch = pa.record_batch({
    "product" : ["Laptop", "Phone", "Tablet", "Monitor"],
    "units"   : [5, 20, 15, 8],
    "price"   : [999.99, 499.99, 299.99, 199.99]
}, schema=schema)

print("RecordBatch:")
print(batch)
print()
print("Rows   :", batch.num_rows)
print("Cols   :", batch.num_columns)
print("Schema :", batch.schema)

"""## Step 4 — Writing to an IPC File

Now we actually **save** the RecordBatch to disk using Arrow's IPC format.

Arrow IPC file format:
- Starts with a **magic number** (identifies it as an Arrow file)
- Then the **schema**
- Then one or more **RecordBatches**
- Ends with a **footer** (index of all batches for fast seeking)

The key function here is `ipc.new_file()` which comes from  
`arrow/python/pyarrow/ipc.pxi` in the Arrow source code.

Docs: https://arrow.apache.org/docs/python/ipc.html#writing-and-reading-ipc-files
"""

import pyarrow as pa
import pyarrow.ipc as ipc
import os

schema = pa.schema([
    pa.field("product", pa.string()),
    pa.field("units",   pa.int32()),
    pa.field("price",   pa.float64())
])

batch = pa.record_batch({
    "product" : ["Laptop", "Phone", "Tablet", "Monitor"],
    "units"   : [5, 20, 15, 8],
    "price"   : [999.99, 499.99, 299.99, 199.99]
}, schema=schema)

print("All set — now run the next cell")

file_path = "products.arrow"

with ipc.new_file(file_path, schema) as writer:
    writer.write_batch(batch)

print(f"File written → {file_path}")
print(f"File size    → {os.path.getsize(file_path)} bytes")
print()
print("This file is now saved in Arrow IPC format on disk.")
print("Anyone with Arrow (Python, R, Java, C++) can read it directly.")

"""## Step 5 — Writing Multiple RecordBatches

In real big data scenarios, data is too large to fit in one batch.  
So Arrow lets us write **multiple batches** into a single file.

Each batch is written one after another.  
The footer at the end of the file keeps track of where each batch starts,  
so Arrow can jump directly to any batch without reading the whole file.

This is what makes Arrow efficient for large files.
"""

batch1 = pa.record_batch({
    "product" : ["Laptop", "Phone"],
    "units"   : [5, 20],
    "price"   : [999.99, 499.99]
}, schema=schema)

batch2 = pa.record_batch({
    "product" : ["Tablet", "Monitor"],
    "units"   : [15, 8],
    "price"   : [299.99, 199.99]
}, schema=schema)

batch3 = pa.record_batch({
    "product" : ["Keyboard", "Mouse"],
    "units"   : [50, 80],
    "price"   : [79.99, 29.99]
}, schema=schema)

multi_file_path = "products_multi.arrow"

with ipc.new_file(multi_file_path, schema) as writer:
    writer.write_batch(batch1)
    writer.write_batch(batch2)
    writer.write_batch(batch3)

print(f"Written 3 batches → {multi_file_path}")
print(f"File size         → {os.path.getsize(multi_file_path)} bytes")

"""## Step 6 — Writing as a Stream (IPC Stream format)

Arrow has two IPC formats:

| Format | Use case |
|---|---|
| IPC File | Save to disk, supports random access |
| IPC Stream | Send over network, reading happens in order |

The stream format does **not** have a footer.  
You read it top to bottom — like reading a file line by line.

This is what tools like Apache Kafka use when sending Arrow data  
between services in a pipeline.

Docs: https://arrow.apache.org/docs/python/ipc.html#writing-and-reading-streams
"""

import io

stream_buffer = io.BytesIO()

with ipc.new_stream(stream_buffer, schema) as stream_writer:
    stream_writer.write_batch(batch1)
    stream_writer.write_batch(batch2)
    stream_writer.write_batch(batch3)

total_bytes = stream_buffer.tell()
print(f"Stream written to memory buffer")
print(f"Total bytes in stream → {total_bytes}")
print()
print("In a real pipeline this stream would go over a network")
print("instead of sitting in memory like we did here.")

"""## Step 7 — Verifying what got written

Let us quickly peek into the file we wrote  
to confirm the schema and batch count are correct.

This is basically the start of the **read path** —  
which we will cover fully in the next notebook.
"""

with ipc.open_file(multi_file_path) as reader:
    print("Schema in file    :", reader.schema)
    print("Number of batches :", reader.num_record_batches)
    print()
    for i in range(reader.num_record_batches):
        b = reader.get_batch(i)
        print(f"  Batch {i} → {b.num_rows} rows")

"""## Write Path — Full Summary

Here is the complete write path we just traced:

pa.array([...])

→ Arrow internally uses ArrayBuilder

→ fills validity bitmap buffer

→ fills value buffer

→ array is ready in memory


pa.record_batch({...}, schema)

→ combines multiple arrays

→ attaches schema

→ one chunk of rows ready to write


ipc.new_file(path, schema)

→ writes magic number to file

→ writes schema block

→ writer.write_batch(batch)

→ serializes each column buffer to disk

→ on close: writes footer (batch index)
"""

