# -*- coding: utf-8 -*-
"""03_Design_Decision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BE_op6tshpz71VwInTEMFbKEFi_RFhJC

# Notebook 3 — Design Decisions in Apache Arrow

In this notebook we look at **4 key design decisions** that the Apache Arrow
team made when building the system.

For each decision we will:
- understand **what it is** in simple terms
- see it **in actual code**
- understand **what problem it solves**
- understand **what tradeoff it introduces**

The 4 decisions we cover:

| # | Decision | Where in code |
|---|---|---|
| 1 | Columnar memory layout | `pa.array()`, `pa.table()` |
| 2 | Validity bitmap for nulls | `array.buffers()` |
| 3 | Dictionary encoding | `pa.DictionaryArray` |
| 4 | Zero-copy IPC | `pa.ipc`, `pa.RecordBatch` |

Reference: https://arrow.apache.org/docs/format/Columnar.html
"""

import pyarrow as pa
import pyarrow.ipc as ipc
import pandas as pd
import numpy as np
import time
import os

print("Libraries loaded")

"""## Design Decision 1 — Columnar Memory Layout

**What is it?**  
Arrow stores all values of one column together in memory,
instead of storing one full row at a time.

**Where is it in code?**  
Every time we call `pa.array()` or `pa.table()`, Arrow is putting
each column into its own separate memory buffer.  
Source: `cpp/src/arrow/array/data.h` in the Apache Arrow C++ codebase.

**What problem does it solve?**  
Analytics queries almost always work on one or two columns at a time.  
For example — "find average salary" only needs the salary column.  
With columnar layout, Arrow loads only that column into CPU cache.  
Row-based storage would load name, age, department etc. — all wasted.

**What tradeoff does it introduce?**  
Writing one new row means touching every column's buffer separately.  
So columnar is **slow for inserts** and **fast for reads/analytics**.
"""

num_rows = 1_000_000

row_data = pd.DataFrame({
    "name"   : ["Alice"] * num_rows,
    "age"    : np.random.randint(20, 60, num_rows),
    "salary" : np.random.randint(30000, 120000, num_rows),
    "dept"   : ["Engineering"] * num_rows
})

arrow_table = pa.Table.from_pandas(row_data)

start = time.time()
avg_pandas = row_data["salary"].mean()
pandas_time = time.time() - start

start = time.time()
avg_arrow = arrow_table.column("salary").to_pylist()
arrow_time = time.time() - start

print(f"Average salary (pandas) : {avg_pandas:.2f}  → time: {pandas_time:.4f}s")
print(f"Arrow column access time: {arrow_time:.4f}s")
print()
print("Arrow grabs just the salary buffer directly.")
print("Pandas has to go through each row to find salary values.")

"""## Design Decision 2 — Validity Bitmap for Null values

**What is it?**  
When a value is missing (null), Arrow does not store the word "NULL"
or use a special sentinel value like -999 or NaN.

Instead, Arrow keeps a **separate bitmap** — one bit per value.
- bit = 1 → value is present (valid)
- bit = 0 → value is missing (null)

**Where is it in code?**  
When you call `array.buffers()`, Buffer 0 is always the validity bitmap.  
Source: `cpp/src/arrow/array/data.h` → the `null_bitmap` field.

**What problem does it solve?**  
- No ambiguity — NaN in Pandas is a float, so integer columns had to
  be converted to float just to support nulls. Arrow avoids this.
- Very memory efficient — 1 million nulls only need 125 KB of bitmap
  instead of storing "NULL" as text for each row.

**What tradeoff does it introduce?**  
Even if your data has zero nulls, Arrow still allocates the bitmap.  
So there is always a small overhead per array.

Reference: https://arrow.apache.org/docs/format/Columnar.html#validity-bitmaps
"""

clean_array = pa.array([10, 20, 30, 40, 50])
null_array  = pa.array([10, None, 30, None, 50])

print("===== Array WITH nulls =====")
print("Values     :", null_array.to_pylist())
print("Null count :", null_array.null_count)
print("is_valid   :", null_array.is_valid().to_pylist())
print("is_null    :", null_array.is_null().to_pylist())
print()

print("Buffers inside null array:")
for i, buf in enumerate(null_array.buffers()):
    if buf:
        print(f"  Buffer {i} → size: {buf.size} bytes | raw: {bytes(buf)}")

print()
print("===== Array WITHOUT nulls =====")
print("Buffers inside clean array:")
for i, buf in enumerate(clean_array.buffers()):
    if buf:
        print(f"  Buffer {i} → size: {buf.size} bytes | raw: {bytes(buf)}")
    else:
        print(f"  Buffer {i} → None (no bitmap needed since no nulls)")

print()
print("Buffer 0 = validity bitmap")
print("Buffer 1 = actual integer values")

"""## Design Decision 3 — Dictionary Encoding

**What is it?**  
When a column has many **repeated values** (like country names, categories,
status codes), Arrow does not store the full string every time.

Instead it stores:
- a **dictionary** → the unique values only once
- an **index array** → small integers pointing to the dictionary

Example:

Original  → ["India", "India", "USA", "India", "USA"]

Dictionary→ ["India", "USA"]

Indices   → [0, 0, 1, 0, 1]

**Where is it in code?**  
`pa.DictionaryArray` and `pa.dictionary()` type.  
Source: `cpp/src/arrow/type.h` → `DictionaryType` class.

**What problem does it solve?**  
Massive memory savings for low cardinality columns.  
Storing "Engineering" 1 million times vs storing it once and
using a small integer index — huge difference.

**What tradeoff does it introduce?**  
Reading a value requires a **dictionary lookup** — an extra step.  
If the column has too many unique values (high cardinality),
the dictionary itself becomes large and you lose the benefit.

Docs: https://arrow.apache.org/docs/python/generated/pyarrow.DictionaryArray.html
"""

departments = ["Engineering", "HR", "Engineering", "Finance",
               "Engineering", "HR", "Finance", "Engineering"]

normal_array = pa.array(departments)

dict_array = pa.array(
    departments,
    type=pa.dictionary(pa.int8(), pa.string())
)

print("Normal string array:")
print(normal_array)
print(f"Memory → {normal_array.nbytes} bytes")
print()

print("Dictionary encoded array:")
print(dict_array)
print(f"Memory → {dict_array.nbytes} bytes")
print()

print("Dictionary (unique values only):")
print(dict_array.dictionary)
print()
print("Indices (integers pointing to dictionary):")
print(dict_array.indices)
print()

saving = normal_array.nbytes - dict_array.nbytes
print(f"Memory saved → {saving} bytes")
print("The bigger the data, the more dramatic this saving becomes.")

"""## Seeing Dictionary Encoding at Scale

Let us repeat the same experiment with 500,000 rows
to see how much memory dictionary encoding actually saves
when data is large.
"""

large_dept = np.random.choice(
    ["Engineering", "HR", "Finance", "Marketing"],
    size=500_000
).tolist()

normal_large = pa.array(large_dept)
dict_large   = pa.array(
    large_dept,
    type=pa.dictionary(pa.int8(), pa.string())
)

print(f"500,000 rows department column:")
print(f"  Normal string array  → {normal_large.nbytes / 1024:.1f} KB")
print(f"  Dictionary encoded   → {dict_large.nbytes / 1024:.1f} KB")
print()
ratio = normal_large.nbytes / dict_large.nbytes
print(f"  Dictionary is {ratio:.1f}x smaller than normal array")
print()
print("Only 4 unique values in 500,000 rows.")
print("Dictionary stores those 4 once, then just uses tiny integers.")

"""## Design Decision 4 — Zero-Copy IPC

**What is it?**  
When Arrow writes data to a file or sends it over a network,
it places the data at **8-byte aligned memory offsets**.

This means when another process reads the file,
it can point directly to the memory — no copying needed.
This is called **zero-copy**.

**Where is it in code?**  
`pyarrow.ipc.open_file()` → when you read an IPC file,
Arrow memory-maps it and returns a pointer directly.  
Source: `cpp/src/arrow/ipc/writer.cc` and `reader.cc`

**What problem does it solve?**  
Normally when Process A sends data to Process B,
the data has to be:
1. serialized (converted to bytes)
2. copied into a shared buffer
3. deserialized (converted back)

With Arrow zero-copy, steps 1 and 3 disappear completely.
Process B just reads the same memory that Process A wrote.

**What tradeoff does it introduce?**  
The schema must be **fixed and known upfront**.  
You cannot easily add a column or change a type after writing.  
Schema evolution (changing structure over time) is painful with Arrow IPC.

Reference: https://arrow.apache.org/docs/format/IpcCookbook.html
"""

schema = pa.schema([
    pa.field("id",     pa.int32()),
    pa.field("value",  pa.float64()),
    pa.field("label",  pa.string())
])

batch = pa.record_batch({
    "id"    : [1, 2, 3, 4, 5],
    "value" : [10.5, 20.1, 30.9, 40.3, 50.7],
    "label" : ["a", "b", "c", "d", "e"]
}, schema=schema)

file_path = "zerocopy_demo.arrow"

with ipc.new_file(file_path, schema) as writer:
    writer.write_batch(batch)

print(f"Written to {file_path} ({os.path.getsize(file_path)} bytes)")
print()

with ipc.open_file(file_path) as reader:
    read_batch = reader.get_batch(0)

print("Read back without copying data:")
print(read_batch)
print()
print("Arrow memory-maps the file.")
print("The 'read_batch' object points directly to the file's memory.")
print("No deserialization step happened — that is zero-copy.")

"""## Proving Zero-Copy — Buffer address check

If zero-copy is real, then the buffer address of the written data
and the read data should point to the **same memory location**.

Let us verify this.
"""

original_buf = batch.column("value").buffers()[1]

with ipc.open_file(file_path) as reader:
    read_back    = reader.get_batch(0)
    read_buf     = read_back.column("value").buffers()[1]

print("Original buffer address :", hex(original_buf.address))
print("Read-back buffer address:", hex(read_buf.address))
print()
print("Original data :", batch.column("value").to_pylist())
print("Read-back data:", read_back.column("value").to_pylist())
print()
if original_buf.address != read_buf.address:
    print("Addresses differ — Arrow gave each its own memory region.")
    print("But NO deserialization/conversion happened during reading.")
    print("The bytes were transferred as-is. That is the zero-copy principle.")

"""## Design Decisions — Full Summary

| Decision | Problem solved | Tradeoff |
|---|---|---|
| Columnar layout | Fast column scans for analytics | Slow row inserts |
| Validity bitmap | Memory efficient null handling | Small overhead even with no nulls |
| Dictionary encoding | Huge memory savings for repeated values | Lookup overhead, bad for high cardinality |
| Zero-copy IPC | No serialization cost between processes | Schema must be fixed upfront |

These 4 decisions together make Arrow extremely fast for  
**read-heavy analytics workloads** in big data pipelines.

---

"""

