# -*- coding: utf-8 -*-
"""04_Concept_Mapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KWamoj2WZkfCDZlG3ycDBnTnJ7HQMRTP

# Notebook 4 — Concept Mapping

In this notebook we connect Apache Arrow to the 4 concepts
taught in class.

We are not just defining these concepts —
we are showing **exactly where and how Arrow implements them**.

| # | Class Concept | How Arrow implements it |
|---|---|---|
| 1 | Columnar Storage | Arrow's core memory format |
| 2 | Partitioning | ChunkedArray and Dataset partitioning |
| 3 | Streaming / Ingestion | Arrow IPC Stream format |
| 4 | Reliability / Fault Tolerance | Schema enforcement + validity bitmap |

Reference: https://arrow.apache.org/docs/python/index.html
"""

import pyarrow as pa
import pyarrow.ipc as ipc
import pyarrow.dataset as ds
import pyarrow.compute as pc
import numpy as np
import os
import io

print("Libraries loaded")

"""## Concept 1 — Columnar Storage

This is the **core concept** behind Apache Arrow.

In traditional row-based storage (like a CSV or Pandas DataFrame),
data is stored one full row at a time in memory.

Arrow flips this completely — it stores one full **column** at a time.

Why does this matter for big data?

Imagine a table with 1 million rows and 20 columns.
If you want to compute the average of one column:
- Row-based → loads all 20 columns × 1M rows into CPU cache
- Columnar  → loads only 1 column × 1M rows into CPU cache

CPU cache is small and precious.
Columnar storage wastes none of it on columns you don't need.

This directly maps to the **B-tree vs LSM vs Columnar** storage
concept from class. Arrow is a pure columnar format — optimized
for reads, not writes.

Reference: https://arrow.apache.org/docs/format/Columnar.html
"""

np.random.seed(42)
n = 500_000

arrow_table = pa.table({
    "employee_id" : np.arange(n),
    "name"        : np.random.choice(["Alice","Bob","Carol","David"], n).tolist(),
    "department"  : np.random.choice(["Eng","HR","Finance"], n).tolist(),
    "salary"      : np.random.randint(30000, 120000, n).tolist(),
    "age"         : np.random.randint(22, 60, n).tolist()
})

print("Table shape:", arrow_table.num_rows, "rows x", arrow_table.num_columns, "columns")
print()

import time

start = time.time()
salary_col = arrow_table.column("salary")
result     = pc.mean(salary_col)
arrow_time = time.time() - start

print(f"Average salary : {result.as_py():.2f}")
print(f"Time taken     : {arrow_time:.5f} seconds")
print()
print("Arrow touched ONLY the salary buffer in memory.")
print("employee_id, name, department, age — never loaded into cache.")
print("This is columnar storage working in practice.")

"""## Concept 2 — Partitioning

**Partitioning** means splitting a large dataset into smaller
independent pieces so they can be processed separately —
possibly in parallel.

Arrow implements partitioning in two ways:

**Way 1 — ChunkedArray**
A single column split into multiple chunks in memory.
Each chunk is a separate buffer.
This lets Arrow process one chunk at a time without
loading the full column.

**Way 2 — Dataset partitioning**
Data split across multiple files on disk,
organized by column values (like one file per department).
Arrow's dataset API reads only the relevant files
for a given query — this is called **partition pruning**.

This maps directly to the **partitioning** concept from class.

Docs: https://arrow.apache.org/docs/python/dataset.html#partitioning
"""

chunk1 = pa.array([1, 2, 3, 4, 5])
chunk2 = pa.array([6, 7, 8, 9, 10])
chunk3 = pa.array([11, 12, 13, 14, 15])

chunked = pa.chunked_array([chunk1, chunk2, chunk3])

print("ChunkedArray:")
print(chunked)
print()
print("Number of chunks :", chunked.num_chunks)
print("Total length     :", len(chunked))
print()

for i, chunk in enumerate(chunked.chunks):
    print(f"  Chunk {i} → {chunk.to_pylist()} | buffer address: {hex(chunk.buffers()[1].address)}")

print()
print("Each chunk lives in its own memory buffer.")
print("Arrow can process chunk 0, chunk 1, chunk 2 independently.")
print("In a distributed system each chunk could go to a different machine.")

"""## Partitioning on Disk — Writing Partitioned Files

This is how real big data systems use Arrow partitioning.

Instead of one giant file, data is split into multiple files
based on the value of a column — for example, one file per department.

When a query asks for only the Engineering department,
Arrow only reads the Engineering file.
The HR and Finance files are never touched.

This is **partition pruning** — skipping files that are not needed.
"""

os.makedirs("partitioned_data/department=Engineering", exist_ok=True)
os.makedirs("partitioned_data/department=HR",          exist_ok=True)
os.makedirs("partitioned_data/department=Finance",     exist_ok=True)

schema = pa.schema([
    pa.field("employee_id", pa.int32()),
    pa.field("salary",      pa.float64())
])

eng_batch = pa.record_batch({
    "employee_id" : [1, 2, 3],
    "salary"      : [90000.0, 95000.0, 88000.0]
}, schema=schema)

hr_batch = pa.record_batch({
    "employee_id" : [4, 5],
    "salary"      : [60000.0, 62000.0]
}, schema=schema)

fin_batch = pa.record_batch({
    "employee_id" : [6, 7, 8],
    "salary"      : [75000.0, 78000.0, 80000.0]
}, schema=schema)

for batch, dept in [(eng_batch, "Engineering"),
                    (hr_batch,  "HR"),
                    (fin_batch, "Finance")]:
    path = f"partitioned_data/department={dept}/data.arrow"
    with ipc.new_file(path, schema) as writer:
        writer.write_batch(batch)
    print(f"Written → {path} ({os.path.getsize(path)} bytes)")

print()
print("Data is now split by department into separate files.")
print("A query for Engineering will ONLY open the Engineering file.")

"""## Concept 3 — Streaming / Ingestion

In real big data pipelines, data does not arrive all at once.
It arrives **continuously** — event by event, batch by batch.

Arrow has a dedicated **IPC Stream format** for this.

Difference between Arrow IPC formats:

| Format | How it works | Use case |
|---|---|---|
| IPC File | Has header + footer, supports random access | Saving to disk |
| IPC Stream | No footer, read top to bottom in order | Network streaming, Kafka |

The stream format is what tools like **Apache Kafka** and
**Apache Flight** use to send Arrow data between services.

This maps to the **Streaming / Ingestion** concept from class.

Docs: https://arrow.apache.org/docs/python/ipc.html#writing-and-reading-streams
"""

stream_schema = pa.schema([
    pa.field("event_id",   pa.int32()),
    pa.field("event_type", pa.string()),
    pa.field("value",      pa.float64())
])

buffer = io.BytesIO()

with ipc.new_stream(buffer, stream_schema) as stream_writer:
    for batch_num in range(5):
        batch = pa.record_batch({
            "event_id"   : [batch_num * 10 + i for i in range(3)],
            "event_type" : np.random.choice(["click","view","purchase"], 3).tolist(),
            "value"      : np.random.uniform(1.0, 100.0, 3).tolist()
        }, schema=stream_schema)

        stream_writer.write_batch(batch)
        print(f"  Batch {batch_num} written → {batch.num_rows} events")

print()
print(f"Total stream size : {buffer.tell()} bytes")
print()
print("In a real pipeline these batches would be sent over a network")
print("one at a time as events arrive — not all at once.")

"""## Reading back the Stream

The receiver reads the stream **batch by batch in order**.
There is no random access — you cannot jump to batch 3
without reading batches 0, 1, and 2 first.

This is exactly how a Kafka consumer works —
it reads messages in order from a topic.
"""

buffer.seek(0)

with ipc.open_stream(buffer) as stream_reader:
    print("Schema received:", stream_reader.schema)
    print()
    batch_num = 0
    for batch in stream_reader:
        print(f"  Received batch {batch_num} → {batch.num_rows} rows")
        print(f"    event_ids : {batch.column('event_id').to_pylist()}")
        batch_num += 1

print()
print("Stream read in order, batch by batch.")
print("This is how Arrow handles continuous data ingestion.")

"""## Concept 4 — Reliability / Fault Tolerance

A system is **reliable** if it handles bad data gracefully
and does not silently produce wrong results.

Arrow builds reliability in two ways:

**Way 1 — Schema enforcement**
Arrow rejects any data that does not match the defined schema.
If a string comes in where an integer is expected, Arrow raises
an error immediately — it does not silently convert or ignore it.

**Way 2 — Validity bitmap**
Every null value is tracked explicitly using a bitmap.
There is no ambiguity about whether a value is missing or just zero.
This prevents the classic NaN bug in Pandas where nulls in integer
columns silently become floats.

Together these two mechanisms ensure that **bad data is caught early**
rather than corrupting results downstream.

This maps to the **Reliability / Fault Tolerance** concept from class.
"""

strict_schema = pa.schema([
    pa.field("user_id", pa.int32()),
    pa.field("score",   pa.float64()),
    pa.field("grade",   pa.string())
])

print("=== Test 1: Correct data — should work fine ===")
try:
    good_batch = pa.record_batch({
        "user_id" : [1, 2, 3],
        "score"   : [88.5, 92.0, 76.3],
        "grade"   : ["B", "A", "C"]
    }, schema=strict_schema)
    print("Passed — data matches schema perfectly\n")
except Exception as e:
    print(f"Failed — {e}\n")

print("=== Test 2: Wrong type — string where int expected ===")
try:
    bad_batch = pa.record_batch({
        "user_id" : ["one", "two", "three"],
        "score"   : [88.5, 92.0, 76.3],
        "grade"   : ["B", "A", "C"]
    }, schema=strict_schema)
    print("Passed\n")
except Exception as e:
    print(f"Rejected by Arrow — {e}\n")

print("=== Test 3: Null handling — explicit and safe ===")
data_with_nulls = pa.record_batch({
    "user_id" : [1, 2, None],
    "score"   : [88.5, None, 76.3],
    "grade"   : ["B", "A", None]
}, schema=strict_schema)

print("Arrow accepted nulls cleanly")
print("user_id nulls :", data_with_nulls.column("user_id").is_null().to_pylist())
print("score nulls   :", data_with_nulls.column("score").is_null().to_pylist())
print()
print("Nulls are tracked in the validity bitmap — not hidden or converted.")

"""## Concept Mapping — Full Summary

| Class Concept | Arrow Implementation | Where in code |
|---|---|---|
| Columnar storage | Each column in its own memory buffer | `pa.array()`, `pa.table()` |
| Partitioning | ChunkedArray + partitioned files on disk | `pa.chunked_array()`, `pyarrow.dataset` |
| Streaming / Ingestion | IPC Stream format — batch by batch | `ipc.new_stream()`, `ipc.open_stream()` |
| Reliability / Fault tolerance | Schema enforcement + validity bitmap | `pa.schema()`, `array.buffers()[0]` |

All 4 concepts are not just theoretical in Arrow —
they are core design choices visible directly in the code.

---

"""

